Update jenkinstask4

diff --git a/jenkins/jenkinstask4 b/jenkins/jenkinstask4
--- a/jenkins/jenkinstask4
+++ b/jenkins/jenkinstask4
@@ -1,21 +1,21 @@
-pipeline{
-agent any
-stages{
-stage('getting user input'){
-steps{
-sh '''
-
-if ${USER} == 'sri' ;
-then
-   echo "the user name is right welcome mr ${USER}"
-else 
-  echo " enther the user name right "
-fi
-
-'''
-}
-}
-}
-}
 
  
+pipeline {
+    agent any
+    
+    stages {
+        stage('User Input and Validation') {
+            steps {
+                sh '''
+                    read -p "Please enter a number: " userInput
+                    if [[ $userInput =~ ^[0-9]+$ ]]; then
+                        echo "You entered a valid number: $userInput"
+                    else
+                        echo "Invalid input. Please enter a valid number."
+                        exit 1
+                    fi
+                '''
+            }
+        }
+    }
+}
